import { describe, expect, test } from 'bun:test'

const html = await Bun.file('src/web/index.html').text()
const app = await Bun.file('src/web/app.ts').text()
const css = await Bun.file('src/web/app.css').text()
const modalEditor = await Bun.file('src/web/editor/modal-editor.ts').text()
const aiClient = await Bun.file('src/domain/ai/owt-ai.ts').text()
const owtReference = await Bun.file('src/domain/owt/reference.ts').text()
const owtDocs = await Bun.file('docs/owt.md').text()
const webBuild = await Bun.file('src/build-web.ts').text()
const sourceHover = await Bun.file('src/web/views/source-hover-view.ts').text()
const keyboardLayout = await Bun.file('src/web/keyboard/layout-view-model.ts').text()

describe('web workspace structure', () => {
  test('integrates score controls into the top bar without a local-session badge', () => {
    const header = html.slice(html.indexOf('<header'), html.indexOf('</header>'))
    expect(header).toContain('id="score-view-toolbar"')
    expect(header).toContain('data-score-view-target="owt"')
    expect(header).toContain('class="control-icon')
    expect(header).toContain('class="control-label"')
    expect(html).not.toContain('class="session-state"')
    expect(html).not.toContain('data-i18n="session.local"')
    expect(app).toContain("control.hidden = pageId !== 'studio'")
    expect(css).toContain('.topbar .control-label { display: none; }')
    expect(html).toContain('<div class="topbar-scroll">')
    expect(html).toContain('<div class="topbar-scroll-content">')
    expect(css).toContain('.topbar-scroll-content { min-width: 100%; width: max-content; flex: 0 0 auto;')
    expect(css).toContain('.topbar-scroll { overflow-x: auto; overflow-y: hidden;')
    expect(css).toContain('.topbar-actions { margin-left: 0; }')
    expect(css).not.toContain('.topbar::-webkit-scrollbar')
    expect(css).not.toContain('grid-template-rows: auto auto auto')
  })

  test('keeps the file menu outside the narrow topbar scroll clip', () => {
    const header = html.slice(html.indexOf('<header'), html.indexOf('</header>'))
    const scrollStart = header.indexOf('<div class="topbar-scroll">')
    expect(header.indexOf('class="file-menu topbar-file-menu"')).toBeLessThan(scrollStart)
    expect(header.indexOf('id="score-view-toolbar"')).toBeGreaterThan(scrollStart)
    expect(header.indexOf('class="topbar-actions"')).toBeGreaterThan(scrollStart)
    expect(css).toContain('.topbar-scroll::-webkit-scrollbar { display: none; }')
  })

  test('orders perform before AI controls and keeps settings after them', () => {
    const header = html.slice(html.indexOf('<header'), html.indexOf('</header>'))
    const toolbar = header.slice(header.indexOf('id="score-view-toolbar"'), header.indexOf('</nav>'))
    expect(header.indexOf('class="file-menu topbar-file-menu"')).toBeLessThan(header.indexOf('id="score-view-toolbar"'))
    expect(toolbar.indexOf('id="btn-owt-practice"')).toBeLessThan(toolbar.indexOf('id="btn-ai-compose"'))
    expect(toolbar.indexOf('id="btn-ai-compose"')).toBeLessThan(toolbar.indexOf('id="btn-ai-improvise"'))
    expect(header.indexOf('id="btn-ai-improvise"')).toBeLessThan(header.indexOf('data-page-target="settings"'))
    const actionsStart = header.indexOf('<div class="topbar-actions">')
    expect(header.indexOf('data-page-target="settings"')).toBeGreaterThan(actionsStart)
    expect(header.indexOf('id="language-toggle"')).toBeGreaterThan(header.indexOf('data-page-target="settings"'))
  })

  test('places a loop toggle beside the global play control', () => {
    const header = html.slice(html.indexOf('<header'), html.indexOf('</header>'))
    expect(header.indexOf('id="btn-score-view-play"')).toBeLessThan(header.indexOf('id="btn-loop-playback"'))
    expect(header.indexOf('id="btn-loop-playback"')).toBeLessThan(header.indexOf('id="btn-owt-practice"'))
    expect(html).toContain('id="btn-loop-playback" class="loop-playback-button topbar-control"')
    expect(html).toContain('data-shortcut="Space t l"')
    expect(app).toContain('engine?.setLooping(loopPlayback)')
    expect(app).toContain('player.setLooping(loopPlayback && allowLoop)')
    expect(app).toContain('playOwtRange(undefined, false)')
    expect(modalEditor).toContain("l: 'loop'")
  })

  test('keeps audition transport in settings and shows one current playback action', () => {
    const header = html.slice(html.indexOf('<header'), html.indexOf('</header>'))
    const play = header.match(/<button id="btn-score-view-play"[^>]*>/)?.[0] ?? ''
    const loop = header.match(/<button id="btn-loop-playback"[^>]*>/)?.[0] ?? ''
    expect(play).not.toContain('data-studio-only')
    expect(loop).not.toContain('data-studio-only')
    for (const id of ['btn-owt-practice', 'btn-ai-compose', 'btn-ai-improvise']) {
      expect(header.match(new RegExp(`<button id="${id}"[^>]*>`))?.[0]).toContain('data-studio-only')
    }
    expect(header).toContain('<div class="score-view-tabs" role="tablist" data-studio-only>')
    expect(play).toContain('data-i18n-aria-label="playback.play"')
    expect(html).toContain('<span class="control-label" data-i18n="playback.play">Play</span>')
    expect(html).not.toContain('>Play / pause</span>')
    expect(app).toContain("const actionKey = playing ? 'playback.pause' : 'playback.play'")
    expect(app).toContain('label.dataset.i18n = actionKey')
  })

  test('uses one global return-to-beginning action instead of stop or settings panic controls', () => {
    const header = html.slice(html.indexOf('<header'), html.indexOf('</header>'))
    const settings = html.slice(html.indexOf('data-workspace-page="settings"'), html.indexOf('</main>'))
    expect(header).toContain('id="btn-return-to-start"')
    expect(header.indexOf('id="btn-loop-playback"')).toBeLessThan(header.indexOf('id="btn-return-to-start"'))
    expect(header).toContain('data-i18n="playback.returnToStart"')
    expect(header).toContain('data-shortcut="Space s"')
    expect(html).not.toContain('id="btn-stop"')
    expect(html).not.toContain('id="btn-restart"')
    expect(settings).not.toContain('id="btn-panic"')
    expect(settings).not.toContain('data-learn="synth-panic"')
    expect(app).toContain('function returnToBeginning()')
    expect(app).toContain("$('btn-return-to-start').addEventListener('click', returnToBeginning)")
    expect(app).toContain("case 'return-to-start': case 'stop': returnToBeginning()")
    expect(modalEditor).toContain("s: 'return-to-start'")
    expect(modalEditor).not.toContain("p: 'panic'")
  })

  test('keeps score editing above the live keyboard in the studio flow', () => {
    const studio = html.slice(html.indexOf('data-workspace-page="studio"'), html.indexOf('data-workspace-page="settings"'))
    expect(studio.indexOf('id="owt-panel"')).toBeGreaterThan(-1)
    expect(studio.indexOf('id="staff-panel"')).toBeGreaterThan(-1)
    expect(studio.indexOf('id="jianpu-panel"')).toBeGreaterThan(-1)
    expect(studio.indexOf('id="live-panel"')).toBeGreaterThan(studio.indexOf('id="jianpu-panel"'))
  })

  test('gives studio controls shortcuts while leaving settings buttons mouse-first', () => {
    const settingsStart = html.indexOf('data-workspace-page="settings"')
    const settingsEnd = html.indexOf('</main>', settingsStart)
    const settings = html.slice(settingsStart, settingsEnd)
    const shortcutScope = `${html.slice(0, settingsStart)}${html.slice(settingsEnd)}`
    const buttons = [...shortcutScope.matchAll(/<button\b[^>]*>/g)].map((match) => match[0])
    expect(buttons.filter((button) => !button.includes('data-shortcut') && !button.includes('aria-keyshortcuts') && !button.includes('data-shortcut-exempt'))).toEqual([])
    expect(buttons.filter((button) => button.includes('data-shortcut-exempt'))).toEqual([
      expect.stringContaining('id="owt-mode"'),
      expect.stringContaining('id="toggle-computer-map"'),
    ])
    expect([...settings.matchAll(/<button\b[^>]*>/g)].map((match) => match[0]).filter((button) => button.includes('data-shortcut') || button.includes('aria-keyshortcuts'))).toEqual([])
    expect(app).toContain("case 'workspace-studio': showWorkspacePage('studio')")
    expect(app).toContain("case 'toggle-locale': localeButton.click()")
    expect(app).toContain("case 'toggle-theme': themeButton.click()")
    expect(app).not.toContain("case 'midi-enable':")
    expect(modalEditor).not.toContain("this.setPending('space-control')")
  })

  test('places an icon-only three-state theme control after the language button', () => {
    const actions = html.slice(html.indexOf('<div class="topbar-actions">'), html.indexOf('</div>', html.indexOf('<div class="topbar-actions">')))
    expect(actions.indexOf('id="theme-toggle"')).toBeGreaterThan(actions.indexOf('id="language-toggle"'))
    expect(actions).toContain('data-theme-state="system"')
    expect(actions).toContain('data-theme-icon="light"')
    expect(actions).toContain('data-theme-icon="dark"')
    expect(actions).toContain('data-theme-icon="system"')
    const themeButton = actions.slice(actions.indexOf('id="theme-toggle"'), actions.indexOf('</button>', actions.indexOf('id="theme-toggle"')))
    expect(themeButton).not.toContain('control-label')
    expect(app).toContain("window.matchMedia('(prefers-color-scheme: dark)')")
    expect(app).toContain("window.localStorage.setItem('opusweave.theme', themePreference)")
    expect(css).toContain(":root[data-effective-theme='light']")
    expect(css).toContain('.topbar-actions button[data-shortcut]::after { display: none; }')
  })

  test('themes staff and Jianpu surfaces in both dark and light modes', () => {
    expect(css).toContain('--notation-bg: #0d100e;')
    expect(css).toContain("--notation-bg: #eeede5;")
    expect(css).toContain('background: var(--notation-bg)')
    expect(css).toContain('stroke: var(--notation-staff-line)')
    expect(css).toContain('color: var(--notation-ink)')
    expect(css).toContain('border-top: 1px solid var(--notation-rule)')
  })

  test('uses a categorized settings center for devices, AI and diagnostics', () => {
    expect(html).toContain('data-page-target="settings"')
    expect(html).toContain('data-workspace-page="settings"')
    expect(html).not.toContain('data-page-target="studio"')
    expect(html).not.toContain('data-page-target="devices"')
    expect(html).not.toContain('data-workspace-page="devices"')
    for (const category of ['general', 'audio', 'midi', 'ai', 'prompts', 'advanced']) {
      expect(html).toContain(`data-settings-target="${category}"`)
      expect(html).toContain(`data-settings-panel="${category}"`)
    }
    expect(html).toContain('id="settings-save-state"')
    expect(html).toContain('id="midi-permission-card"')
    expect(html).toContain('id="ai-provider"')
    expect(html).toContain('class="prompt-workbench"')
    expect(html).not.toContain('id="record-panel"')
    expect(html).not.toContain('id="btn-record"')
    expect(css).toContain('.settings-shell {')
    expect(css).toContain('.settings-nav-item.active')
  })

  test('fetches FluidR3Mono as a non-blocking, separately cached built-in bank', () => {
    expect(app).toContain("import builtInGmSoundFontUrl from './assets/soundfonts/FluidR3Mono_GM.sf3' with { type: 'file' }")
    expect(app).toContain('const gmResponsePromise = fetch(builtInGmSoundFontUrl)')
    expect(app).toContain("setBuiltInSoundFontState('unavailable')")
    expect(app).not.toContain('await builtInSoundFontPromise')
    expect(html).toContain('id="built-in-soundfont" data-state="loading"')
    expect(html).toContain('id="btn-retry-built-in-soundfont"')
    expect(webBuild).toContain("!entry.name.toLowerCase().endsWith('.sf3')")
    expect(app).not.toContain('opusweave-micro-gm.sf2')
  })

  test('offers official optional SoundFont downloads in settings', () => {
    for (const id of ['btn-download-musescore-general', 'btn-download-generaluser', 'btn-download-timgm']) {
      expect(html).toContain(`id="${id}"`)
    }
    expect(html).not.toContain('data-shortcut="Space k 4"')
    expect(app).not.toContain("case 'soundfont-musescore':")
    expect(modalEditor).not.toContain("'4': 'soundfont-musescore'")
  })

  test('opens AI composition through one button and a modal prompt dialog', () => {
    expect(html.match(/id="btn-ai-compose"/g)).toHaveLength(1)
    expect(html).toContain('<dialog id="ai-compose-dialog"')
    expect(html).toContain('id="ai-prompt"')
    expect(html).toContain('id="btn-ai-submit"')
    expect(app).toContain('aiComposeDialog.showModal()')
    expect(app).toContain("setAiComposeState('working')")
    expect(app).toContain("setAiComposeState('success')")
    expect(app).toContain("setAiComposeState('error')")
    expect(html).toContain('id="ai-reasoning-panel"')
    expect(html).toContain('id="ai-reasoning-last-line"')
    expect(html).toContain('class="ai-reasoning-stream"')
    expect(app).toContain('onReasoningUpdate')
    expect(aiClient).toContain('onReasoningUpdate')
    expect(app).toContain("const unavailable = !active && !configured")
    expect(app).toContain("button.disabled = unavailable || (aiBusy && !active)")
    expect(css).toContain(".ai-improv-button:disabled")
    expect(css).toContain(".ai-improv-button[data-improv-state='thinking'] { border-color: rgba(198, 165, 246, 0.55)")
    expect(css).toContain('@keyframes ai-improv-pulse')
    expect(css).toContain(":root[data-effective-theme='light'] .ai-compose-button")
  })

  test('submits composition on Enter and exposes persistent per-feature prompt templates', () => {
    expect(app).toContain("if (event.key !== 'Enter' || event.shiftKey || event.isComposing) return")
    expect(app).toContain('aiComposeForm.requestSubmit()')
    for (const id of ['ai-template-system', 'ai-template-prompt', 'ai-template-media', 'ai-template-improvise']) {
      expect(html).toContain(`id="${id}"`)
    }
    expect(html).toContain('id="btn-ai-reset-templates"')
    expect(app).toContain('promptTemplates: currentAiPromptTemplates()')
    expect(aiClient).toContain("buildOwt01Reference('en')")
  })

  test('tests prompt templates through live model requests and reports validated OWT results', () => {
    expect(html).toContain('id="ai-prompt-test-dialog"')
    expect(html).toContain('id="ai-prompt-test-results"')
    expect(app).toContain('const promptTestCases = [')
    expect(app).toContain("id: 'compose'")
    expect(app).toContain("id: 'edit'")
    expect(app).toContain("id: 'continue'")
    expect(app).toContain('await createOwtWithAi(config,')
    expect(app).toContain('const parsed = parseOwt(text)')
    expect(app).toContain("track.events.filter((event) => event.kind === 'note')")
    expect(app).toContain("card.classList.replace('running', 'passed')")
    expect(app).not.toContain('buildOwtAiMessages(request, config)')
  })

  test('collapses four score views into one cycling button on narrow screens', () => {
    expect(html.match(/<button class="score-view-tab/g)).toHaveLength(4)
    expect(html).toContain('id="btn-score-view-cycle"')
    expect(html).toContain('data-shortcut="Space g n"')
    expect(css).toContain('.topbar .score-view-cycle { display: none;')
    expect(css).toContain('.score-view-tabs { display: none; }')
    expect(css).toContain('.topbar .score-view-cycle { display: inline-flex; }')
    expect(app).toContain("const SCORE_VIEW_ORDER: readonly ScoreViewId[] = ['owt', 'timeline', 'staff', 'jianpu']")
    expect(app).toContain('scoreViewCycleButton.addEventListener(\'click\', cycleScoreView)')
    expect(app).toContain("case 'view-next': cycleScoreView(); return")
    expect(modalEditor).toContain("n: 'view-next'")
  })

  test('renders the timeline only from the current OWT score', () => {
    const timeline = html.slice(html.indexOf('id="playback-panel"'), html.indexOf('id="staff-panel"'))
    expect(timeline).toContain('id="timeline-tracks"')
    expect(timeline).not.toContain('btn-export-arrangement')
    expect(timeline).not.toContain('btn-replace-range')
    expect(timeline).not.toContain('btn-clear-range')
    expect(app).toContain('timelineModel = buildScoreViewModel(result.document)')
    expect(app).toContain('for (const measure of track.measures)')
    expect(app).not.toContain('replaceArrangementRange')
    expect(app).not.toContain('loadMidiData')
    expect(css).toContain('.arranger-grid.has-score .arranger-empty')
    expect(css).not.toContain('.arranger-grid.has-midi .arranger-empty')
  })

  test('opens the same built-in OWT reference for people and AI', () => {
    expect(owtReference).toContain('OWT 0.1 — COMPLETE FORMAT REFERENCE')
    expect(owtReference).toContain('OWT 0.1——完整格式参考')
    expect(html).toContain('id="btn-owt-reference"')
    expect(html).toContain('data-shortcut="Space ?"')
    expect(html).toContain('<dialog id="owt-reference-dialog"')
    expect(html).toContain('id="owt-reference-content"')
    expect(html).toContain('id="btn-owt-reference-copy"')
    expect(app).toContain("$('owt-reference-content').textContent = buildOwt01Reference(getLocale())")
    expect(app).toContain("case 'help': showOwtReferenceDialog(); return")
    expect(aiClient).toContain("owtReference: buildOwt01Reference(locale)")
    expect(aiClient).toContain("defaultOwtAiPromptTemplates(locale")
  })

  test('randomizes composition suggestions and submits the visible suggestion when empty', () => {
    const prompt = html.match(/<textarea id="ai-prompt"[^>]*>/)?.[0] ?? ''
    expect(prompt).not.toContain('required')
    expect(app).toContain("ai.promptExample.rain")
    expect(app).toContain("ai.promptExample.typhoon")
    expect(app).toContain('aiPrompt.placeholder = chooseAiPromptExample()')
    expect(app).toContain('aiPrompt.value.trim() || aiPrompt.placeholder.trim()')
  })

  test('persists the current OWT in a shareable URL hash', () => {
    expect(app).toContain("import { decodeOwtHash, encodeOwtHash } from './owt-url-state.ts'")
    expect(app).toContain('syncOwtUrlHash(owtEditor.value)')
    expect(app).toContain('window.history.replaceState')
    expect(app).toContain('const initialOwtFromHash = decodeOwtHash(window.location.hash)')
    expect(app).toContain('setOwtEditorText(initialOwtFromHash ?? DEFAULT_OWT_SCORE)')
    expect(app).toContain("window.addEventListener('hashchange'")
    expect(app).toContain('if (initialOwtFromHash === null)')
  })

  test('uses manual AI collaboration when no optional API is configured', () => {
    const checkedSources = `${html}\n${app}\n${aiClient}\n${owtDocs}`
    expect(checkedSources).not.toMatch(/\b(?:10\.\d{1,3}|192\.168|172\.(?:1[6-9]|2\d|3[01]))(?:\.\d{1,3}){2}\b/)
    expect(html).not.toMatch(/id="ai-endpoint"[^>]*\svalue=/)
    expect(html).not.toMatch(/id="ai-model"[^>]*\svalue=/)
    expect(html).toContain('id=\"ai-protocol\"')
    expect(html).toContain('id=\"ai-model-options\"')
    expect(html).toContain('id=\"btn-ai-refresh-models\"')
    expect(app).toContain('discoverAiModels(config')
    expect(html).toContain('<dialog id="ai-manual-dialog"')
    expect(html).toContain('id="ai-manual-prompt"')
    expect(html).toContain('id="btn-ai-manual-copy"')
    expect(app).toContain('if (!hasConfiguredAiApi(currentAiConfig()))')
    expect(app).toContain('buildManualOwtPrompt(owtEditor.value, getLocale())')
    expect(app).toContain('navigator.clipboard.writeText(aiManualPrompt.value)')
    expect(modalEditor).toContain("textarea.addEventListener('paste'")
  })

  test('uses provider-first AI configuration with progressive generation parameters', () => {
    expect(html).toContain('id="ai-provider"')
    expect(html).toContain('<option value="deepseek">DeepSeek</option>')
    expect(html).toContain('id="ai-model" type="text"')
    expect(html).toContain('class="settings-more-parameters"')
    for (const id of ['ai-thinking-mode', 'ai-reasoning-effort', 'ai-temperature', 'ai-top-p', 'ai-max-tokens', 'ai-thinking-budget']) {
      expect(html).toContain(`id="${id}"`)
    }
    expect(app).toContain("thinkingMode: thinkingMode ? thinkingMode as NonNullable<OwtAiConfig['thinkingMode']> : undefined")
    expect(app).toContain("reasoningEffort: reasoningEffort ? reasoningEffort as NonNullable<OwtAiConfig['reasoningEffort']> : undefined")
    expect(app).toContain("deepseek: { baseUrl: 'https://api.deepseek.com', protocol: 'openai-chat-completions' }")
    expect(app).not.toContain("'/api/ai/chat'")
    expect(aiClient).toContain("reasoning: { effort: openAiEffort }")
    expect(aiClient).toContain("output_config: { effort: anthropicEffort }")
    expect(aiClient).toContain("{ think }")
  })

  test('keeps contextual motion help inside the focused OWT editor', () => {
    expect(html).toContain('id="owt-motion-destinations"')
    expect(html).not.toContain('class="owt-motion-hints"')
    expect(html).not.toContain('id="owt-event-input"')
    expect(html).not.toContain('data-i18n="ai.improvHint"')
    expect(css).toContain('.owt-motion-destination')
    expect(css).toContain('.owt-motion-target')
    expect(html).toContain('id="owt-status" class="status" hidden')
    expect(html).toContain('data-shortcut="d"')
    expect(html).not.toContain('data-shortcut="Space a d"')
    expect(modalEditor).toContain("case 'd': void this.callbacks.onCommand('delete-object')")
    expect(app).not.toContain("owtEditor.addEventListener('click'")
  })

  test('switches NORMAL and RAW from the lower-left mode indicator', () => {
    expect(html.match(/id="btn-ai-improvise"/g)).toHaveLength(1)
    expect(html.indexOf('id="btn-ai-improvise"')).toBeLessThan(html.indexOf('</header>'))
    expect(html).not.toContain('id="btn-owt-mode-score"')
    expect(html).not.toContain('id="btn-owt-mode-raw"')
    expect(html).not.toContain('class="owt-edit-mode-tabs"')
    expect(html).toContain('<button id="owt-mode" class="owt-mode normal"')
    expect(app).toContain("$('owt-mode').addEventListener('click'")
    expect(modalEditor).toContain("{ s: 'mode-score', r: 'mode-raw' }")
    expect(css).not.toContain('.owt-editor-shell.raw .owt-highlight')
    expect(css).not.toContain('.owt-editor-shell.raw .owt-editor')
  })

  test('moves file and MIDI import options out of the editor chrome', () => {
    expect(html).toContain('class="file-menu topbar-file-menu"')
    expect(html.match(/id="owt-file"/g)).toHaveLength(1)
    expect(html).toContain('id="owt-example-menu"')
    expect(html).not.toContain('id="owt-example"')
    expect(html).not.toContain('id="btn-load-example"')
    expect(html).not.toContain('class="score-open-actions"')
    expect(html).not.toContain('class="example-picker"')
    expect(app).toContain("button.dataset.exampleId = example.id")
    expect(html).toContain('class="file-submenu-popover example-menu-list"')
    expect(css).toContain('.file-submenu-popover { width: 290px;')
    expect(css).toContain('left: calc(100% + 8px); z-index: 31;')
    expect(css).toContain('.file-submenu:not([open]) > .file-submenu-popover { display: none; }')
    expect(css).toContain('.file-menu-popover button { width: 100%; border: 0;')
    expect(css).toContain('.file-menu-item, .topbar .file-menu-popover > button')
    expect(css).toContain('.file-menu-popover button:hover:not(:disabled)')
    expect(html).toContain('id="midi-import-dialog"')
    expect(html).toContain('id="owt-grid"')
    expect(html.indexOf('id="owt-grid"')).toBeGreaterThan(html.indexOf('id="midi-import-dialog"'))
    expect(html).not.toContain('class="owt-actions"')
    expect(html).not.toContain('class="owt-source-row"')
  })

  test('uses F5 as a global play and pause shortcut', () => {
    expect(html).toContain('data-shortcut="F5 · Space p"')
    expect(html).toContain('aria-keyshortcuts="F5"')
    expect(app).toContain('if (ev.ctrlKey || ev.metaKey || ev.altKey) return')
    expect(app).not.toContain("ev.code === 'Space'")
    expect(app).toContain("ev.key === 'F5'")
    expect(app).toContain("handleModalCommand('play-pause')")
  })

  test('keeps guided performance visible in the top toolbar', () => {
    const header = html.slice(html.indexOf('<header'), html.indexOf('</header>'))
    expect(header).toContain('id="btn-owt-practice"')
    expect(header).toContain('data-shortcut="Space q"')
    expect(header).toContain('aria-pressed="false"')
    expect(html.match(/id="btn-owt-practice"/g)).toHaveLength(1)
    expect(html).not.toContain('id="btn-owt-practice" class="sr-only"')
    expect(app).toContain('function updatePracticeButton()')
  })

  test('merges octave and velocity controls into the keyboard-map header', () => {
    const livePanel = html.slice(html.indexOf('id="live-panel"'), html.indexOf('</section>', html.indexOf('id="live-panel"')))
    const mapHeader = livePanel.slice(livePanel.indexOf('class="computer-map-head"'), livePanel.indexOf('class="computer-map-content"'))
    expect(mapHeader).toContain('id="oct-down"')
    expect(mapHeader).toContain('id="oct-label"')
    expect(mapHeader).toContain('id="velocity-down"')
    expect(mapHeader).toContain('id="key-velocity"')
    expect(mapHeader).toContain('id="computer-layout"')
    expect(mapHeader).toContain('class="map-shortcut-hint"')
    expect(mapHeader).toContain('id="toggle-computer-map"')
    expect(mapHeader).not.toContain('data-shortcut="Space k m"')
    expect(modalEditor).not.toContain("m: 'toggle-key-map'")
    expect(app).not.toContain("case 'toggle-key-map'")
    expect(css).toContain(".map-toggle[aria-expanded='false'] .map-toggle-icon")
    expect(mapHeader).toContain('id="live-notes"')
    const mapContent = livePanel.slice(livePanel.indexOf('class="computer-map-content"'))
    expect(mapContent).not.toContain('id="computer-layout"')
    expect(livePanel).not.toContain('data-i18n="section.instrument"')
    expect(livePanel).not.toContain('data-i18n="section.livePerformance"')
    expect(livePanel).not.toContain('class="hint keyboard-hint"')
    expect(app).not.toContain('updateComputerLayoutGuidance')
  })

  test('renders layout-specific key maps including the complete FreePiano keyboard', () => {
    expect(html).not.toContain('class="bridge-label"')
    expect(html).not.toContain('data-i18n="live.mappingBridge"')
    expect(keyboardLayout).toContain("id: 'navigation'")
    expect(keyboardLayout).toContain("id: 'numpad'")
    expect(keyboardLayout).toContain("['numlock', 'num/', 'num*', 'num-']")
    expect(keyboardLayout).toContain("['num0', 'num.', null]")
    expect(keyboardLayout).toContain('rowOffsets: [0, 1.5, 1.75, 2.25]')
    expect(keyboardLayout).toContain('rowOffsets: [0, 0.25, 0.75, 2]')
    expect(app).toContain("root.dataset.layout = layout")
    expect(app).toContain("row.style.setProperty('--keyboard-row-offset'")
    expect(app).toContain('minNote: 0')
    expect(app).toContain('maxNote: 127')
    expect(app).not.toContain('keyboard.setRange(')
    expect(app).not.toContain('traceActiveOnly')
    expect(css).toContain('.keyboard-map-section + .keyboard-map-section')
    expect(css).toContain('margin-inline-start: var(--keyboard-row-offset, 0px)')
    expect(app).toContain('if (!assignment && !action)')
    expect(app).not.toContain("keycap.classList.add('unmapped')")
    expect(css).not.toContain('.computer-keycap.unmapped')
  })

  test('explains hovered score source as a readable multiline field list', () => {
    expect(html).toContain('id="source-hover-card"')
    expect(html).toContain('id="source-hover-raw"')
    expect(html).toContain('id="source-hover-fields"')
    expect(sourceHover).toContain('function describeOwtSourceToken(raw: string')
    expect(app).toContain('attachSourceHover(block, raw')
    expect(app).toContain('attachSourceHover(element, raw')
    expect(app).not.toContain('block.title = `${noteName(note.note)}')
    expect(css).toContain('.source-hover-card dl')
    expect(css).toContain('white-space: pre-wrap')
  })

  test('groups the preset picker into localized GM families with emoji labels', () => {
    expect(app).toContain("emoji: '🎹', key: 'sound.family.piano'")
    expect(app).toContain("emoji: '🎻', key: 'sound.family.strings'")
    expect(app).toContain("emoji: '🎺', key: 'sound.family.brass'")
    expect(app).toContain("emoji: '🌌', key: 'sound.family.synthPad'")
    expect(app).toContain("emoji: '🥁', key: 'sound.family.percussive'")
    expect(app).toContain("group = document.createElement('optgroup')")
    expect(app).toContain('group.label = `${family.emoji} ${t(family.key)}`')
    expect(app).toContain('appendGroupedPresets(sel, patches)')
  })

  test('confirms AI-bound file imports before reading or sending the file', () => {
    expect(html).toContain('<dialog id="ai-media-import-dialog"')
    expect(html).toContain('id="ai-media-file-name"')
    expect(html).toContain('id="ai-media-mode"')
    expect(html).toContain('id="ai-media-frames"')
    expect(html).toContain('id="ai-media-prompt"')
    expect(html).toContain('id="btn-ai-media-confirm"')
    expect(app).toContain('else requestAiMediaImport(file)')
    expect(app).toContain('aiMediaImportDialog.showModal()')
    expect(app).toContain('mediaFileToAiAttachments(file, options.maxVideoFrames)')
    expect(app).toContain("includeCurrentScore: aiMediaMode.value === 'edit'")
    const requestStart = app.indexOf('function requestAiMediaImport(file: File)')
    const requestEnd = app.indexOf('function cancelAiMediaImport()', requestStart)
    expect(app.slice(requestStart, requestEnd)).not.toContain('mediaFileToAiAttachments')
  })
  test('shows OWT repair only for validation errors and exposes AI repair settings', () => {
    expect(html).toContain('id="btn-owt-repair"')
    expect(html.match(/<button id="btn-owt-repair"[^>]*>/)?.[0]).toContain('hidden')
    expect(html).toContain('id="owt-repair-options"')
    expect(html).toContain('id="owt-repair-split-events" type="checkbox"')
    expect(html).not.toMatch(/id="owt-repair-split-events"[^>]*checked/)
    expect(app).toContain("diagnostics.some((diagnostic) => diagnostic.severity === 'error')")
    expect(app).toContain("'btn-owt-repair').hidden = !owtHasErrors")
    expect(app).toContain('splitCrossBoundaryEvents')
    expect(html).toContain('id="ai-retry-count"')
    expect(html).toContain('id="ai-retry-count" type="number" min="0" max="10" step="1" value="0"')
    expect(html).toContain('id="ai-auto-repair"')
    expect(html).toContain('id="btn-ai-test-templates"')
    expect(app).toContain('repairCommonOwtErrors(owtEditor.value, { splitCrossBoundaryEvents })')
  })

})
