/**
 * Generates src/web/models-directory.ts from models.dev's API JSON.
 *
 * Usage:
 *   bun scripts/generate-models-directory.ts [path-to-models-dev.json]
 *
 * The input defaults to https://models.dev/api.json. The generated module is a
 * static, dependency-free snapshot so the browser does not need network access
 * to show the built-in model catalog.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const inputPath = Bun.argv[2]
let raw: string
if (inputPath) {
  raw = await Bun.file(inputPath).text()
} else {
  const response = await fetch('https://models.dev/api.json')
  if (!response.ok) throw new Error(`Failed to fetch models.dev: ${response.status}`)
  raw = await response.text()
}

const data = JSON.parse(raw) as Record<string, {
  id?: string
  name?: string
  api?: string
  env?: string[]
  npm?: string
  models?: Record<string, ModelRecord>
}>

interface ModelRecord {
  id?: string
  name?: string
  reasoning?: boolean
  reasoning_options?: Array<{ type?: string; values?: string[] }>
  tool_call?: boolean
  structured_output?: boolean
  temperature?: boolean
  attachment?: boolean
  modalities?: { input?: string[]; output?: string[] }
  limit?: { context?: number; output?: number }
  cost?: { input?: number; output?: number; cache_read?: number }
}

type Protocol = 'openai-responses' | 'openai-chat-completions' | 'openai-completions' | 'anthropic-messages' | 'ollama-native'

const KNOWN_API: Record<string, { api: string; protocol: Protocol }> = {
  openai: { api: 'https://api.openai.com/v1', protocol: 'openai-responses' },
  anthropic: { api: 'https://api.anthropic.com/v1', protocol: 'anthropic-messages' },
  deepseek: { api: 'https://api.deepseek.com', protocol: 'openai-chat-completions' },
  openrouter: { api: 'https://openrouter.ai/api/v1', protocol: 'openai-chat-completions' },
  'ollama-cloud': { api: 'https://ollama.com/v1', protocol: 'openai-chat-completions' },
}

function inferProtocol(providerId: string, npm: string | undefined, api: string | undefined): Protocol | null {
  if (KNOWN_API[providerId]) return KNOWN_API[providerId]!.protocol
  if (!api) return null
  const sdk = npm ?? ''
  if (sdk.includes('openai-compatible')) return 'openai-chat-completions'
  if (sdk.includes('anthropic')) return 'anthropic-messages'
  if (sdk === '@ai-sdk/openai') return 'openai-responses'
  if (sdk === '@openrouter/ai-sdk-provider') return 'openai-chat-completions'
  return null
}

interface ProviderOut {
  id: string
  name: string
  api: string
  env?: string[]
  protocol: Protocol
  models: ModelOut[]
}

interface ModelOut {
  id: string
  name: string
  context?: number
  output?: number
  reasoning?: boolean
  reasoningOptions?: string[]
  temperature?: boolean
  attachment?: boolean
  toolCall?: boolean
  structuredOutput?: boolean
  modalities?: string[]
  cost?: { input?: number; output?: number; cache_read?: number }
}

const providers: ProviderOut[] = []

for (const [id, provider] of Object.entries(data)) {
  const api = KNOWN_API[id]?.api ?? provider.api
  const protocol = inferProtocol(id, provider.npm, api)
  if (!protocol || !api) continue
  const models = Object.entries(provider.models ?? {}).flatMap(([modelId, model]): ModelOut[] => {
    const realId = model.id ?? modelId
    const reasoningOptions = model.reasoning_options
      ?.flatMap((option) => option.type === 'effort' ? (option.values ?? []) : option.type === 'toggle' ? ['toggle'] : [])
      .filter((value): value is string => typeof value === 'string')
    return [{
      id: realId,
      name: model.name ?? realId,
      context: model.limit?.context,
      output: model.limit?.output,
      reasoning: model.reasoning,
      reasoningOptions: reasoningOptions && reasoningOptions.length > 0 ? [...new Set(reasoningOptions)] : undefined,
      temperature: model.temperature,
      attachment: model.attachment,
      toolCall: model.tool_call,
      structuredOutput: model.structured_output,
      modalities: model.modalities?.input && model.modalities.input.length > 0 ? model.modalities.input : undefined,
      cost: model.cost ? {
        input: model.cost.input,
        output: model.cost.output,
        cache_read: model.cost.cache_read,
      } : undefined,
    }]
  })
  if (models.length === 0) continue
  providers.push({
    id,
    name: provider.name ?? id,
    api,
    env: provider.env && provider.env.length > 0 ? provider.env : undefined,
    protocol,
    models,
  })
}

providers.sort((a, b) => a.name.localeCompare(b.name))

const output = `/**
 * Built-in model directory snapshot generated from models.dev.
 *
 * This file is generated by scripts/generate-models-directory.ts; do not edit
 * by hand. It contains only providers that OpusWeave can speak to with a
 * supported protocol (OpenAI-compatible, Anthropic Messages, or Responses).
 */
export type ModelDirectoryProtocol = 'openai-responses' | 'openai-chat-completions' | 'openai-completions' | 'anthropic-messages' | 'ollama-native'

export interface ModelDirectoryCost {
  input?: number
  output?: number
  cache_read?: number
}

export interface ModelDirectoryModel {
  id: string
  name: string
  context?: number
  output?: number
  reasoning?: boolean
  reasoningOptions?: string[]
  temperature?: boolean
  attachment?: boolean
  toolCall?: boolean
  structuredOutput?: boolean
  modalities?: string[]
  cost?: ModelDirectoryCost
}

export interface ModelDirectoryProvider {
  id: string
  name: string
  api: string
  env?: string[]
  protocol: ModelDirectoryProtocol
  models: ModelDirectoryModel[]
}

export const modelDirectory: ModelDirectoryProvider[] = ${JSON.stringify(providers, null, 2)}
`

const outPath = resolve(import.meta.dir, '../src/web/models-directory.ts')
writeFileSync(outPath, output)
console.log(`Wrote ${outPath} (${providers.length} providers, ${providers.reduce((n, p) => n + p.models.length, 0)} models)`)
